services:
  backend:
    build: ./Backend
    container_name: ai-backend
    restart: always
    environment:
      - AIORTC_ICE_SERVERS=turn:openrelay.metered.ca:80?transport=udp&username=openrelayproject&credential=openrelayproject

  frontend-builder:
    build: ./Frontend
    command: sh -c "npm install && npm run build"
    volumes:
      - ./Frontend:/app
      - frontend_build:/app/build
    restart: "no"

  nginx:
    image: nginx:alpine
    container_name: ai-nginx
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-builder

volumes:
  frontend_build: